import '../../core/models/learning_item.dart';

const hurufItems = [
  LearningItem(title: 'A', subtitle: 'A untuk Apel', visual: '🍎'),
  LearningItem(title: 'B', subtitle: 'B untuk Bola', visual: '⚽'),
  LearningItem(title: 'C', subtitle: 'C untuk Cicak', visual: '🦎'),
  LearningItem(title: 'D', subtitle: 'D untuk Domba', visual: '🐑'),
  LearningItem(title: 'E', subtitle: 'E untuk Elang', visual: '🦅'),
  LearningItem(title: 'F', subtitle: 'F untuk Flamingo', visual: '🦩'),
  LearningItem(title: 'G', subtitle: 'G untuk Gajah', visual: '🐘'),
  LearningItem(title: 'H', subtitle: 'H untuk Harimau', visual: '🐯'),
  LearningItem(title: 'I', subtitle: 'I untuk Ikan', visual: '🐟'),
  LearningItem(title: 'J', subtitle: 'J untuk Jeruk', visual: '🍊'),
  LearningItem(title: 'K', subtitle: 'K untuk Kucing', visual: '🐱'),
  LearningItem(title: 'L', subtitle: 'L untuk Lampu', visual: '💡'),
  LearningItem(title: 'M', subtitle: 'M untuk Mobil', visual: '🚗'),
  LearningItem(title: 'N', subtitle: 'N untuk Nanas', visual: '🍍'),
  LearningItem(title: 'O', subtitle: 'O untuk Obat', visual: '💊'),
  LearningItem(title: 'P', subtitle: 'P untuk Pisang', visual: '🍌'),
  LearningItem(title: 'Q', subtitle: 'Q untuk Queen', visual: '👑'),
  LearningItem(title: 'R', subtitle: 'R untuk Roti', visual: '🍞'),
  LearningItem(title: 'S', subtitle: 'S untuk Sapi', visual: '🐄'),
  LearningItem(title: 'T', subtitle: 'T untuk Topi', visual: '🎩'),
  LearningItem(title: 'U', subtitle: 'U untuk Ular', visual: '🐍'),
  LearningItem(title: 'V', subtitle: 'V untuk Vas', visual: '🏺'),
  LearningItem(title: 'W', subtitle: 'W untuk Wortel', visual: '🥕'),
  LearningItem(title: 'X', subtitle: 'X untuk Xilofon', visual: '🎼'),
  LearningItem(title: 'Y', subtitle: 'Y untuk Yo-yo', visual: '🪀'),
  LearningItem(title: 'Z', subtitle: 'Z untuk Zebra', visual: '🦓'),
];

const angkaItems = [
  LearningItem(title: '1', subtitle: 'Satu', visual: '🍎'),
  LearningItem(title: '2', subtitle: 'Dua', visual: '🍎🍎'),
  LearningItem(title: '3', subtitle: 'Tiga', visual: '🍎🍎🍎'),
  LearningItem(title: '4', subtitle: 'Empat', visual: '🍎🍎🍎🍎'),
  LearningItem(title: '5', subtitle: 'Lima', visual: '⭐️⭐️⭐️⭐️⭐️'),
  LearningItem(title: '6', subtitle: 'Enam', visual: '🟡🟡🟡🟡🟡🟡'),
  LearningItem(title: '7', subtitle: 'Tujuh', visual: '🌸🌸🌸🌸🌸🌸🌸'),
  LearningItem(title: '8', subtitle: 'Delapan', visual: '🐟🐟🐟🐟🐟🐟🐟🐟'),
  LearningItem(title: '9', subtitle: 'Sembilan', visual: '🍪🍪🍪🍪🍪🍪🍪🍪🍪'),
  LearningItem(title: '10', subtitle: 'Sepuluh', visual: '🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈'),
];

const hijaiyahItems = [
  LearningItem(title: 'ا', subtitle: 'Alif', visual: '🌙'),
  LearningItem(title: 'ب', subtitle: 'Ba', visual: '⭐'),
  LearningItem(title: 'ت', subtitle: 'Ta', visual: '🌸'),
  LearningItem(title: 'ث', subtitle: 'Tsa', visual: '🌷'),
  LearningItem(title: 'ج', subtitle: 'Jim', visual: '🕌'),
  LearningItem(title: 'ح', subtitle: 'Ha', visual: '☀️'),
  LearningItem(title: 'خ', subtitle: 'Kha', visual: '☁️'),
  LearningItem(title: 'د', subtitle: 'Dal', visual: '🌙'),
  LearningItem(title: 'ذ', subtitle: 'Dzal', visual: '⭐'),
  LearningItem(title: 'ر', subtitle: 'Ra', visual: '🌸'),
  LearningItem(title: 'ز', subtitle: 'Zai', visual: '🌷'),
  LearningItem(title: 'س', subtitle: 'Sin', visual: '🕌'),
  LearningItem(title: 'ش', subtitle: 'Syin', visual: '☀️'),
  LearningItem(title: 'ص', subtitle: 'Shad', visual: '🌙'),
  LearningItem(title: 'ض', subtitle: 'Dhad', visual: '⭐'),
  LearningItem(title: 'ط', subtitle: 'Tha', visual: '🌸'),
  LearningItem(title: 'ظ', subtitle: 'Zha', visual: '🌷'),
  LearningItem(title: 'ع', subtitle: 'Ain', visual: '🕌'),
  LearningItem(title: 'غ', subtitle: 'Ghain', visual: '☀️'),
  LearningItem(title: 'ف', subtitle: 'Fa', visual: '🌙'),
  LearningItem(title: 'ق', subtitle: 'Qaf', visual: '⭐'),
  LearningItem(title: 'ك', subtitle: 'Kaf', visual: '🌸'),
  LearningItem(title: 'ل', subtitle: 'Lam', visual: '🌷'),
  LearningItem(title: 'م', subtitle: 'Mim', visual: '🕌'),
  LearningItem(title: 'ن', subtitle: 'Nun', visual: '☀️'),
  LearningItem(title: 'و', subtitle: 'Wawu', visual: '🌙'),
  LearningItem(title: 'ه', subtitle: 'Ha', visual: '⭐'),
  LearningItem(title: 'لا', subtitle: 'Lam Alif', visual: '🌸'),
  LearningItem(title: 'ي', subtitle: 'Ya', visual: '🌷'),
];

const gambarItems = [
  LearningItem(title: 'Kucing', subtitle: 'Hewan', visual: '🐱', category: 'Hewan'),
  LearningItem(title: 'Anjing', subtitle: 'Hewan', visual: '🐶', category: 'Hewan'),
  LearningItem(title: 'Gajah', subtitle: 'Hewan', visual: '🐘', category: 'Hewan'),
  LearningItem(title: 'Singa', subtitle: 'Hewan', visual: '🦁', category: 'Hewan'),
  LearningItem(title: 'Ikan', subtitle: 'Hewan', visual: '🐟', category: 'Hewan'),
  LearningItem(title: 'Apel', subtitle: 'Buah', visual: '🍎', category: 'Buah'),
  LearningItem(title: 'Pisang', subtitle: 'Buah', visual: '🍌', category: 'Buah'),
  LearningItem(title: 'Jeruk', subtitle: 'Buah', visual: '🍊', category: 'Buah'),
  LearningItem(title: 'Anggur', subtitle: 'Buah', visual: '🍇', category: 'Buah'),
  LearningItem(title: 'Semangka', subtitle: 'Buah', visual: '🍉', category: 'Buah'),
  LearningItem(title: 'Mobil', subtitle: 'Kendaraan', visual: '🚗', category: 'Kendaraan'),
  LearningItem(title: 'Bus', subtitle: 'Kendaraan', visual: '🚌', category: 'Kendaraan'),
  LearningItem(title: 'Kereta', subtitle: 'Kendaraan', visual: '🚆', category: 'Kendaraan'),
  LearningItem(title: 'Pesawat', subtitle: 'Kendaraan', visual: '✈️', category: 'Kendaraan'),
  LearningItem(title: 'Rumah', subtitle: 'Benda', visual: '🏠', category: 'Benda'),
  LearningItem(title: 'Buku', subtitle: 'Benda', visual: '📚', category: 'Benda'),
  LearningItem(title: 'Jam', subtitle: 'Benda', visual: '⏰', category: 'Benda'),
  LearningItem(title: 'Bola', subtitle: 'Benda', visual: '⚽', category: 'Benda'),
];

const warnaItems = [
  LearningItem(title: 'Merah', subtitle: 'Warna Merah', visual: '🔴', colorHex: '#EF5350'),
  LearningItem(title: 'Biru', subtitle: 'Warna Biru', visual: '🔵', colorHex: '#42A5F5'),
  LearningItem(title: 'Kuning', subtitle: 'Warna Kuning', visual: '🟡', colorHex: '#FFD54F'),
  LearningItem(title: 'Hijau', subtitle: 'Warna Hijau', visual: '🟢', colorHex: '#66BB6A'),
  LearningItem(title: 'Ungu', subtitle: 'Warna Ungu', visual: '🟣', colorHex: '#AB47BC'),
  LearningItem(title: 'Oranye', subtitle: 'Warna Oranye', visual: '🟠', colorHex: '#FF9800'),
  LearningItem(title: 'Merah Muda', subtitle: 'Warna Pink', visual: '🩷', colorHex: '#F48FB1'),
  LearningItem(title: 'Cokelat', subtitle: 'Warna Cokelat', visual: '🟤', colorHex: '#8D6E63'),
  LearningItem(title: 'Putih', subtitle: 'Warna Putih', visual: '⚪', colorHex: '#FFFFFF'),
  LearningItem(title: 'Hitam', subtitle: 'Warna Hitam', visual: '⚫', colorHex: '#37474F'),
];
