import '../../core/models/learning_item.dart';

const List<LearningItem> hurufItems = [
  LearningItem(title: 'A', visual: '🍎', sound: 'A. Apel'),
  LearningItem(title: 'B', visual: '⚽', sound: 'B. Bola'),
  LearningItem(title: 'C', visual: '🐊', sound: 'C. Cicak'),
  LearningItem(title: 'D', visual: '🦆', sound: 'D. Bebek'),
  LearningItem(title: 'E', visual: '🐘', sound: 'E. Gajah'),
  LearningItem(title: 'F', visual: '🌸', sound: 'F. Bunga'),
  LearningItem(title: 'G', visual: '🐱', sound: 'G. Kucing'),
  LearningItem(title: 'H', visual: '🐟', sound: 'H. Ikan'),
  LearningItem(title: 'I', visual: '🌞', sound: 'I. Matahari'),
  LearningItem(title: 'J', visual: '🚗', sound: 'J. Mobil'),
  LearningItem(title: 'K', visual: '🍌', sound: 'K. Pisang'),
  LearningItem(title: 'L', visual: '🏠', sound: 'L. Rumah'),
  LearningItem(title: 'M', visual: '⭐', sound: 'M. Bintang'),
  LearningItem(title: 'N', visual: '🌈', sound: 'N. Pelangi'),
  LearningItem(title: 'O', visual: '🦁', sound: 'O. Singa'),
  LearningItem(title: 'P', visual: '🐼', sound: 'P. Panda'),
  LearningItem(title: 'Q', visual: '🐰', sound: 'Q. Kelinci'),
  LearningItem(title: 'R', visual: '🐮', sound: 'R. Sapi'),
  LearningItem(title: 'S', visual: '🐢', sound: 'S. Kura kura'),
  LearningItem(title: 'T', visual: '🌷', sound: 'T. Tulip'),
  LearningItem(title: 'U', visual: '🍇', sound: 'U. Anggur'),
  LearningItem(title: 'V', visual: '🐯', sound: 'V. Harimau'),
  LearningItem(title: 'W', visual: '🍉', sound: 'W. Semangka'),
  LearningItem(title: 'X', visual: '🎁', sound: 'X. Hadiah'),
  LearningItem(title: 'Y', visual: '🚀', sound: 'Y. Roket'),
  LearningItem(title: 'Z', visual: '🦓', sound: 'Z. Zebra'),
];

const List<LearningItem> angkaItems = [
  LearningItem(title: '1', visual: '⭐', sound: 'Angka satu'),
  LearningItem(title: '2', visual: '⭐⭐', sound: 'Angka dua'),
  LearningItem(title: '3', visual: '⭐⭐⭐', sound: 'Angka tiga'),
  LearningItem(title: '4', visual: '⭐⭐⭐⭐', sound: 'Angka empat'),
  LearningItem(title: '5', visual: '⭐⭐⭐⭐⭐', sound: 'Angka lima'),
  LearningItem(title: '6', visual: '⭐⭐⭐⭐⭐⭐', sound: 'Angka enam'),
  LearningItem(title: '7', visual: '⭐⭐⭐⭐⭐⭐⭐', sound: 'Angka tujuh'),
  LearningItem(title: '8', visual: '⭐⭐⭐⭐⭐⭐⭐⭐', sound: 'Angka delapan'),
  LearningItem(title: '9', visual: '⭐⭐⭐⭐⭐⭐⭐⭐⭐', sound: 'Angka sembilan'),
  LearningItem(title: '10', visual: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', sound: 'Angka sepuluh'),
];

const List<LearningItem> hijaiyahItems = [
  LearningItem(title: 'ا', visual: 'ا', sound: 'Alif'),
  LearningItem(title: 'ب', visual: 'ب', sound: 'Ba'),
  LearningItem(title: 'ت', visual: 'ت', sound: 'Ta'),
  LearningItem(title: 'ث', visual: 'ث', sound: 'Tsa'),
  LearningItem(title: 'ج', visual: 'ج', sound: 'Jim'),
  LearningItem(title: 'ح', visual: 'ح', sound: 'Ha'),
  LearningItem(title: 'خ', visual: 'خ', sound: 'Kha'),
  LearningItem(title: 'د', visual: 'د', sound: 'Dal'),
  LearningItem(title: 'ذ', visual: 'ذ', sound: 'Dzal'),
  LearningItem(title: 'ر', visual: 'ر', sound: 'Ra'),
  LearningItem(title: 'ز', visual: 'ز', sound: 'Zai'),
  LearningItem(title: 'س', visual: 'س', sound: 'Sin'),
  LearningItem(title: 'ش', visual: 'ش', sound: 'Syin'),
  LearningItem(title: 'ص', visual: 'ص', sound: 'Shad'),
  LearningItem(title: 'ض', visual: 'ض', sound: 'Dhad'),
  LearningItem(title: 'ط', visual: 'ط', sound: 'Tha'),
  LearningItem(title: 'ظ', visual: 'ظ', sound: 'Zha'),
  LearningItem(title: 'ع', visual: 'ع', sound: 'Ain'),
  LearningItem(title: 'غ', visual: 'غ', sound: 'Ghain'),
  LearningItem(title: 'ف', visual: 'ف', sound: 'Fa'),
  LearningItem(title: 'ق', visual: 'ق', sound: 'Qaf'),
  LearningItem(title: 'ك', visual: 'ك', sound: 'Kaf'),
  LearningItem(title: 'ل', visual: 'ل', sound: 'Lam'),
  LearningItem(title: 'م', visual: 'م', sound: 'Mim'),
  LearningItem(title: 'ن', visual: 'ن', sound: 'Nun'),
  LearningItem(title: 'و', visual: 'و', sound: 'Wau'),
  LearningItem(title: 'ه', visual: 'ه', sound: 'Ha'),
  LearningItem(title: 'لا', visual: 'لا', sound: 'Lam Alif'),
  LearningItem(title: 'ي', visual: 'ي', sound: 'Ya'),
];

const List<LearningItem> gambarItems = [
  LearningItem(title: 'Kucing', visual: '🐱', sound: 'Kucing'),
  LearningItem(title: 'Anjing', visual: '🐶', sound: 'Anjing'),
  LearningItem(title: 'Gajah', visual: '🐘', sound: 'Gajah'),
  LearningItem(title: 'Singa', visual: '🦁', sound: 'Singa'),
  LearningItem(title: 'Ikan', visual: '🐟', sound: 'Ikan'),
  LearningItem(title: 'Apel', visual: '🍎', sound: 'Apel'),
  LearningItem(title: 'Pisang', visual: '🍌', sound: 'Pisang'),
  LearningItem(title: 'Jeruk', visual: '🍊', sound: 'Jeruk'),
  LearningItem(title: 'Anggur', visual: '🍇', sound: 'Anggur'),
  LearningItem(title: 'Semangka', visual: '🍉', sound: 'Semangka'),
  LearningItem(title: 'Mobil', visual: '🚗', sound: 'Mobil'),
  LearningItem(title: 'Bus', visual: '🚌', sound: 'Bus'),
  LearningItem(title: 'Kereta', visual: '🚆', sound: 'Kereta'),
  LearningItem(title: 'Pesawat', visual: '✈️', sound: 'Pesawat'),
  LearningItem(title: 'Rumah', visual: '🏠', sound: 'Rumah'),
  LearningItem(title: 'Buku', visual: '📚', sound: 'Buku'),
  LearningItem(title: 'Jam', visual: '⏰', sound: 'Jam'),
  LearningItem(title: 'Bola', visual: '⚽', sound: 'Bola'),
];

const List<LearningItem> warnaItems = [
  LearningItem(title: 'Merah', visual: '🔴', sound: 'Warna merah'),
  LearningItem(title: 'Biru', visual: '🔵', sound: 'Warna biru'),
  LearningItem(title: 'Kuning', visual: '🟡', sound: 'Warna kuning'),
  LearningItem(title: 'Hijau', visual: '🟢', sound: 'Warna hijau'),
  LearningItem(title: 'Ungu', visual: '🟣', sound: 'Warna ungu'),
  LearningItem(title: 'Oranye', visual: '🟠', sound: 'Warna oranye'),
  LearningItem(title: 'Merah Muda', visual: '🩷', sound: 'Warna merah muda'),
  LearningItem(title: 'Cokelat', visual: '🟤', sound: 'Warna cokelat'),
  LearningItem(title: 'Putih', visual: '⚪', sound: 'Warna putih'),
  LearningItem(title: 'Hitam', visual: '⚫', sound: 'Warna hitam'),
];
